[project]
name = "discord-service-config"
authors = [
    { name = "It was then i started gettin lost in books", email = "noemail@gmail.com" }
    ]
version = "1.1.2+gitfix"
requires-python = ">=3.11"
dependencies = [
    "psutil>=7.1.1",
    "PyGetWindow>=0.0.9",
    "pypresence>=4.6.1",
    "starlark>=0.6.0",
    "watchdog>=6.0.0"
]

[project.optional-dependencies]
dev = [
    "ruff",
    "mypy",
    "build",
]

[tool.ruff]
exclude = [
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    "build",
    "dist",
    "*.egg-info",
]

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "RUF"]
ignore = ["RUF001", "RUF002", "RUF003"]
