import sys
from typing import Any


class iint:
    def __init__(self, value: str | int | float) -> None:
        self._int = int(value)
        self._string = str(self._int)
        self._float = float(self._int)
        ...

    def __iter__(self) -> iint: ...
    def __add__(self, other) -> str | float | iint: ...
    def __radd__(self, other) -> str | float | iint: ...
    def __str__(self) -> str: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __bool__(self) -> bool: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __abs__(self) -> int: ...
    def __and__(self, other) -> Any: ...
    if sys.version_info >= (3, 8):
        def as_integer_ratio(self): ...
        "In future"