# =========================================================
# Create by ddeeaaddllyy (https://github.com/ddeeaaddllyy)
# All rights reserved
# UNDER APACHE-2.0 AND GPLv3 LICENSE
# =========================================================
import sys
from _typeshed import Self
from typing import Any, Iterable


class iint:
    def __init__(self, value: str | int | float) -> None:
        self._int = int(value)
        self._string = str(self._int)
        self._float = float(self._int)
        ...

    def __abs__(self) -> int: ...
    def __add__(self, other) -> str | float | iint: ...
    def __and__(self, other) -> Any: ...
    def __bool__(self) -> bool: ...
    def __ceil__(self): ...
    def __class__(self: Self) -> type[Self]: ...
    def __delattr__(self, item): ...
    def __dir__(self) -> Iterable[str]: ...
    def __divmod__(self, other): ...
    def __doc__(self): ...
    def __eq__(self, other): ...
    def __float__(self) -> float: ...
    def __floor__(self): ...
    def __floordiv__(self, other): ...
    def __format__(self, format_spec) -> str: ...
    def __ge__(self, other): ...
    def __getattribute__(self, item): ...
    def __getnewargs__(self): ...
    def __getstate__(self): ...
    def __gt__(self, other): ...
    def __hash__(self): ...
    def __index__(self): ...
    def __init_subclass__(cls, **kwargs): ...
    def __int__(self) -> int: ...
    def __invert__(self): ...
    def __le__(self, other): ...
    def __len__(self) -> int: ...
    def __lshift__(self, other): ...
    def __lt__(self, other): ...
    def __mod__(self, other): ...
    def __mul__(self, other): ...
    def __ne__(self, other): ...
    def __neg__(self) -> int: ...
    def __new__(cls, *args, **kwargs): ...
    def __or__(self, other): ...
    def __pos__(self) -> int: ...
    def __pow__(self, power, modulo=None): ...
    def __radd__(self, other) -> str | float | iint: ...
    def __rand__(self, other): ...
    def __rdivmod__(self, other): ...
    def __reduce__(self): ...
    def __reduce_ex__(self, protocol): ...
    def __repr__(self) -> str: ...
    def __rfloordiv__(self, other): ...
    def __rlshift__(self, other): ...
    def __rmod__(self, other): ...
    def __rmul__(self, other): ...
    def __ror__(self, other): ...
    def __round__(self, n=None): ...
    def __rpow__(self, other): ...
    def __rrshift__(self, other): ...
    def __rshift__(self, other): ...
    def __rsub__(self, other): ...
    def __rtruediv__(self, other): ...
    def __rxor__(self, other): ...
    def __setattr__(self, key, value): ...
    def __sizeof__(self): ...
    def __str__(self) -> str: ...
    def __sub__(self, other): ...
    def __subclasscheck__(self, subclass): ...
    def __truediv__(self, other): ...
    def __trunc__(self): ...
    def __xor__(self, other): ...
    def __iter__(self) -> iint: ...
    def __hex__(self) -> str: ...

    # Custom functions
    def to_int(self) -> int: ...
    def to_str(self) -> str: ...
    def to_float(self) -> float: ...
    if sys.version_info >= (3, 8):
        def as_integer_ratio(self): ...
    def bit_count(self): ...
    def bit_length(self): ...
    def conjugate(self): ...
    def denominator(self): ...
    def from_bytes(self): ...
    def imag(self): ...
    def numerator(self): ...
    def real(self): ...
    def to_bytes(self): ...
